package com.aamir.service;

import com.aamir.*;
import com.aamir.entity.Student;
import com.aamir.exception.GrpcExceptionHandler;
import com.aamir.exception.GrpcStudentNotFoundException;
import com.aamir.repo.StudentRepository;
import io.grpc.stub.StreamObserver;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.grpc.server.service.GrpcService;

import java.util.List;
import java.util.Optional;

@GrpcService
@RequiredArgsConstructor
@Slf4j
public class StudentServiceImpl extends StudentServiceGrpc.StudentServiceImplBase {

    private final StudentRepository studentRepository;

    @Override
    public void createStudent(StudentRequest request, StreamObserver<StudentResponse> responseObserver) {

        // 1️⃣ Build a Student entity from the incoming gRPC request.
        // The request object contains data sent by the client (name, email, etc.).
        Student student = Student.builder()
                .name(request.getName()) // get the student's name from the request
                .email(request.getEmail()) // get the student's email from the request
                .build(); // build the Student entity (without id yet)

        // 2️⃣ Save the Student entity to the database using the studentRepository (likely a JPA repository).
        // After saving, the 'student' will now have an autogenerated ID from the DB.
        student = studentRepository.save(student);

        // 3️⃣ Log a message showing that the student was saved, including the generated ID.
        log.info("Saved Student with id {}", student.getId());

        // 4️⃣ Build a StudentResponse to send back to the client.
        // This response includes the id, name, and email of the newly saved student.
        StudentResponse response = StudentResponse.newBuilder()
                .setId(student.getId()) // set the student id in the response
                .setName(student.getName()) // set the student name in the response
                .setEmail(student.getEmail()) // set the student email in the response
                .build(); // build the response object

        // 5️⃣ Send the response back to the client.
        // onNext() sends the response data over the gRPC stream.
        responseObserver.onNext(response);

        // 6️⃣ Mark the RPC call as completed.
        // This tells the client that the server is done sending responses.
        responseObserver.onCompleted();

    }

    @Override
    public void getStudentById(StudentIdRequest request, StreamObserver<StudentResponse> responseObserver) {
        try {
            // 1️⃣ Attempt to fetch the student by ID from the database.
            // The request object carries the student ID sent by the client.
            Optional<Student> studentOptional = studentRepository.findById(request.getId());

            // 2️⃣ Check if the student exists using ifPresentOrElse:
            studentOptional.ifPresentOrElse(
                    student -> {
                        // ✅ CASE: Student found
                        // Build the response containing the student details.
                        StudentResponse response = StudentResponse.newBuilder()
                                .setId(student.getId()) // set student ID in the response
                                .setName(student.getName()) // set student name in the response
                                .setEmail(student.getEmail()) // set student email in the response
                                .build(); // build the response object

                        // Send the response to the client.
                        responseObserver.onNext(response);

                        // Mark the RPC as completed.
                        responseObserver.onCompleted();
                    },
                    () -> {
                        // ❌ CASE: Student not found
                        // Throw a custom gRPC exception indicating student was not found.
                        // This will be caught in the catch block below.
                        throw new GrpcStudentNotFoundException("Student not found with ID: " + request.getId());
                    }
            );
        } catch (Exception e) {
            // 3️⃣ If any exception occurs (including the custom not-found case),
            // handle it using a custom exception handler that maps it to a proper gRPC error response.
            responseObserver.onError(GrpcExceptionHandler.handleException(e));
        }
    }

    @Override
    public void getAllStudents(Empty request, StreamObserver<StudentList> responseObserver) {
        // 1️⃣ Fetch all student records from the database using your repository.
        List<Student> studentList = studentRepository.findAll();

        // 2️⃣ Transform each Student entity into a StudentResponse (the gRPC message format).
        //    - We use a Java Stream to map each Student to a StudentResponse.
        //    - For each student:
        //        - set the ID, name, and email.
        //    - Collect the results as a List of StudentResponse objects.
        List<StudentResponse> list = studentList.stream()
                .map(student -> StudentResponse.newBuilder()
                        .setId(student.getId())      // Set the student's ID
                        .setName(student.getName())  // Set the student's name
                        .setEmail(student.getEmail())// Set the student's email
                        .build())                    // Build the StudentResponse
                .toList();                           // Collect to a List

        // 3️⃣ Build the StudentList message (which contains the list of StudentResponse messages).
        StudentList allStudentResponse = StudentList.newBuilder()
                .addAllStudents(list) // Add all students to the response (repeated field)
                .build();             // Build the StudentList message

        // 4️⃣ Send the full StudentList back to the client.
        responseObserver.onNext(allStudentResponse);

        // 5️⃣ Mark the RPC as completed (no more messages will be sent).
        responseObserver.onCompleted();
    }


    @Override
    public void deleteStudentById(StudentIdRequest request, StreamObserver<DeleteResponse> responseObserver) {
        // 1️⃣ Delete the student record by ID from the repository.
        //    - Here we are calling the repository's deleteById() method, which will delete the student with the provided ID.
        studentRepository.deleteById(request.getId());

        // 2️⃣ Create a response message to indicate successful deletion.
        //    - "Deleted Successfully" is the message that will be sent back to the client.
        DeleteResponse deleteResponse = DeleteResponse.newBuilder()
                .setMessage("Deleted Successfully")  // Set the success message in the response
                .build();                           // Build the DeleteResponse object

        // 3️⃣ Send the response back to the client using the responseObserver.
        //    - This tells the client that the delete operation was successful.
        responseObserver.onNext(deleteResponse);

        // 4️⃣ Mark the RPC as completed.
        //    - No further messages will be sent after this.
        responseObserver.onCompleted();
    }


    @Override
    public void updateStudentById(StudentRequest request, StreamObserver<StudentResponse> responseObserver) {
        try {
            // 1️⃣ Try to find the student by ID using the studentRepository.
            Optional<Student> studentOptional = studentRepository.findById(request.getId());

            // 2️⃣ If the student is found, proceed to update their details.
            studentOptional.ifPresentOrElse(student -> {
                // 2.1️⃣ Update the student's name and email with the data from the request.
                student.setName(request.getName());
                student.setEmail(request.getEmail());

                // 2.2️⃣ Save the updated student details to the repository.
                student = studentRepository.save(student);

                // 2.3️⃣ Build the response using the updated student data.
                StudentResponse response = StudentResponse.newBuilder()
                        .setId(student.getId())      // Set the student's ID in the response
                        .setName(student.getName())  // Set the updated student's name
                        .setEmail(student.getEmail())// Set the updated student's email
                        .build();                    // Build the StudentResponse message

                // 2.4️⃣ Send the updated student response to the client.
                responseObserver.onNext(response);

                // 2.5️⃣ Complete the RPC call after sending the response.
                responseObserver.onCompleted();
            }, () -> {
                // 3️⃣ If the student is not found, throw a custom exception.
                throw new GrpcStudentNotFoundException("Student not found with ID: " + request.getId());
            });
        } catch (Exception e) {
            // 4️⃣ If any error occurs during the process, handle it and send the error response to the client.
            responseObserver.onError(GrpcExceptionHandler.handleException(e));
        }
    }

}
